#The VS Projects generated by CMAKE are configured with an installation prefix that points to the 
#Winlua installer Deploy directory. See cmake-init-libressl.ps1 for more details.
#This script requires vsvars.ps1 to work. It can be found in sources/winlua-luarocks.
msbuild INSTALL.vcxproj
